### ISSUE TITLE
Unknown device ID report

### ISSUE THREAD

**Issue by Clearmist** [libmtp/libmtp#168]
## Nintendo Switch
vendorID 0x057E
productID 0x3000

## Nintendo Switch in MTP mode
vendorID 0x057E
productID 0x201D

**Comment by msmeissn** [comment]
The second USB id is in GIT since 1.1.19 release.

The first id, not sure what  mode it is talking there, do you know if it also talks PTP or MTP? Or Mass Storage?

(lsusb -v    in this mode and extract the part of the switch)

**Comment by Clearmist** [comment]
Hi msmeissn :) This vendor and product combination is what is reported by the device when running an application called DBI on the Switch and choosing to connect to the backend server. A different product ID (201d) is used when DBI uses MTP mode.

`057e:3000  DBI`

`057e:3000 (bus 1, device 2) path: 3`

```yaml
Using libusb v1.0.26.11724

Opening device 057E:3000...

Device properties:
        bus number: 1
         port path: 3 (from root hub)
             speed: 480 Mbit/s (USB HighSpeed)

Reading device descriptor:
            length: 18
      device class: 0
               S/N: 3
           VID:PID: 057E:3000
         bcdDevice: 0100
   iMan:iProd:iSer: 1:2:3
          nb confs: 1

Reading BOS descriptor: 2 caps
    USB 2.0 extension:
      attributes             : 02
    USB 3.0 capabilities:
      attributes             : 00
      supported speeds       : 000E
      supported functionality: 03

Reading first configuration descriptor:
              total length: 32
         descriptor length: 9
             nb interfaces: 1
              interface[0]: id = 0
interface[0].altsetting[0]: num endpoints = 2
   Class.SubClass.Protocol: FF.FF.FF
       endpoint[0].address: 81
           max packet size: 0200
          polling interval: 00
       endpoint[1].address: 01
           max packet size: 0200
          polling interval: 00

Kernel driver attached for interface 0: -12

Claiming interface 0...

Reading string descriptors:
   String (0x01): "-"
   String (0x02): "DBI"
   String (0x03): "XAW10070513829"

Reading OS string descriptor: no descriptor

Releasing interface 0...
Closing device...
```
